### ISSUE TITLE
README.mdの中のコマンドで、『-rm』は『--rm』に訂正をお願いします

### ISSUE THREAD

**Issue by teamsawww** [fuku-youtube/php-mysql-docker#1]
Saw aka @teamsawwwと申します。YouTubeで、『DockerでPHP・MySQL開発環境を構築しよう！【Mac編】part2』で勉強させて頂きました。概要欄に、「PHPのソースはこちらをご覧ください」と書いてあったので、こちらから、色々なファイルの中身もコピペさせて頂きました。
その中で、READEME.mdで2箇所、『-rm』という部分があるコマンドがあり、そのままコピペして実行したところ、ターミナルに叱られました。YouTubeの動画の中では『--rm』となっていましたので、その箇所を『--rm』にしたところ、うまくいきましたので、ご報告します。
YouTubeの動画の方は正しいので、こちらでコメントした方がいいのかな、と思いました。
これからコピペする方々のために訂正してくださると幸いです。どうぞよろしく。
とてもわかりやすい動画で知りたかったことが学べて大変喜んでいます。どうもありがとうございます!

**Comment by fuku-youtube** [comment]
@teamsawww 
issueあげてくださりありがとうございます！
上記の内容は修正いたします！

**Comment by fuku-youtube** [comment]
こちらで対応させていただきましたのでCloseいたします！
https://github.com/fuku-youtube/php-mysql-docker/commit/ea7c3e2cec0b457059ec4d619d46a105fcee7ee0

**Comment by teamsawww** [comment]
ありがとうございます！😃🙏
